name: Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy via SSH
        uses: peaceiris/actions-gh-pages@v3
        with:
          ssh_private_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          commit_message: "Deploy Hugo site via SSH"
